### ISSUE TITLE
Web browser testing for ChRIS UI on an iPhone

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-chris#24]
![Hackathon Task for Team-19 Hackathon 2021](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Team-19 Hackathon 2021")

# Web browser testing for ChRIS UI on an iPhone

### Task description: 

Web browser testing for ChRIS UI on an iPhone

**Comment by KatherinePMI** [comment]
[Web browser testing for ChRIS UI on an iPhone.docx](https://github.com/team19hackathon2021/issues-chris/files/7421052/Web.browser.testing.for.ChRIS.UI.on.an.iPhone.docx)
