### ISSUE TITLE
Web browser testing for ChRIS UI on an iPad

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-chris#26]
![Hackathon Task for Team-19 Hackathon 2021](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Team-19 Hackathon 2021")

# Web browser testing for ChRIS UI on an iPad

### Task description: 

Web browser testing for ChRIS UI on an iPad

**Comment by KatherinePMI** [comment]
ChRIS UI = https://app.chrisproject.org/

**Comment by KatherinePMI** [comment]
[Web browser testing for ChRIS UI on an iPad.docx](https://github.com/team19hackathon2021/issues-chris/files/7421036/Web.browser.testing.for.ChRIS.UI.on.an.iPad.docx)
