### ISSUE TITLE
Package pfcon in the Red Hat Container Catalog

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-chris#29]
![Hackathon Task for Team-19 Hackathon 2021](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Team-19 Hackathon 2021")

# Package pfcon in the Red Hat Container Catalog

### Task description: 

Help ease-of-use in standing up the ChRIS platform would be to get two core backend components of ChRIS - pfcon - packaged for and listed in the Red Hat Container Catalog (or some other public container registry if another one is deemed more suitable.) The end goal is making it easier to get ChRIS up and running on OpenShift.

**Comment by germanodasilva** [comment]
The best way would be to build an operator, it's not part of the purpose of the hackaton but I can leave the structure built. Help with adoption?

**Comment by germanodasilva** [comment]
https://github.com/team19hackathon2021/ChRIS_operator

**Comment by computate** [comment]
An OpenShift operator sounds awesome. I'm not experinced with OpenShift operators, but if you have experience there, we'd love those kind of contributions @germanodasilva !

**Comment by adambkaplan** [comment]
Do we even need the images in the Red Hat Container Catalog? The container catalog is for container images that either:

1. Are productized by Red Hat, OR
2. Are offered as a product/service by Red Hat's ISV partners.

For something that is intended for community adoption, pushing the images to any public container registry is sufficient. The operator can then be submitted to [operatorhub.io](https://operatorhub.io/).

**Comment by germanodasilva** [comment]
Guys, just to reassure you.

The Operator must be deployed on the operatorhub.io itself.
It is the community's project catalog.

Operator Code runs on any K8S, at a future time the operator needs to be published to operatorhub.io, which currently has a very intuitive interface to use. (I can help too)

What will need to be decided is in which registry the container images will be stored, for the sake of simplicity you can create the organization within quay.io

**Comment by adambkaplan** [comment]
I think this issue can be closed. pfcon is already building and pushing to DockerHub - `docker.io/fnndsc/pfcon:latest` [1][2]

[1] https://hub.docker.com/r/fnndsc/pfcon/tags
[2] https://github.com/team19hackathon2021/pfcon/blob/master/.github/workflows/ci.yml#L74-L83

**Comment by adambkaplan** [comment]
Note that Docker Hub imposes rate limits on anonymous image pulls. To avoid this, developers should add a Docker Hub image pull secret to their cluster.
