### ISSUE TITLE
Package pman in the Red Hat Container Catalog

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-chris#30]
![Hackathon Task for Team-19 Hackathon 2021](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Team-19 Hackathon 2021")

# Package pman in the Red Hat Container Catalog

### Task description: 

Help ease-of-use in standing up the ChRIS platform would be to get two core backend components of ChRIS - pman - packaged for and listed in the Red Hat Container Catalog (or some other public container registry if another one is deemed more suitable.) The end goal is making it easier to get ChRIS up and running on OpenShift.

**Comment by adambkaplan** [comment]
To get ChRIS running on OpenShift, one only needs a container image in an easily accessible location. There's a high barrier to entry to get something onto the Red Hat Container Catalog - those images are either productized by Red Hat or are certified by ISV partners.

There is already a public container image for pman on Docker Hub - `docker.io/fnndsc/pman` [1]. This can be deployed on OpenShift fairly easily. It should be noted that at scale, cluster admins should configure a pull secret to Docker Hub to avoid their rate limiting.

[1] https://hub.docker.com/r/fnndsc/pman
