### ISSUE TITLE
create an Ansible Playbook to setup everything

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-chris#36]
# Mission create an Ansible Playbook to setup everything

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for ChRIS")

Your mission, should you choose to accept it, is create an Ansible Playbook to setup everything. 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

ChRIS is a pervasively open source platform that utilizes cloud technologies to democratize medical analytics application development. It enables healthcare organizations to keep owning their data while benefiting from public cloud processing capabilities. ChRIS is developed as part of a collaborative effort between Boston Children’s Hospital, Red Hat, Boston University, and the Mass Open Cloud (MOC). ChRIS allows researchers the ability to simply deploy their applications in a cloud infrastructure with access to more data, more compute, and more collaboration to drive medical innovation. ChRIS uses leading open source technologies to standardize cloud-based healthcare application development, taking care of the infrastructure so medical researchers can focus on their data.

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/ChRIS_ultron_backEnd/tree/master/ansible

## Define the playbook to run locally. 

Create a new file: /usr/local/src/ChRIS_ultron_backEnd/ansible/install_all.yml

```plain
---
# Define the playbook to run locally. 
- name: Install the ChRIS containers locally in podman with Ansible
  connection: local
  hosts: localhost

```

## Call the all the  ChRIS Ansible roles. 

```plain

  # Call the all the  ChRIS Ansible roles. 
  roles:
    - chris_defaults
    - chris_before
    - chris_dev_db
    - chris_pman
    - chris_pfcon
    - chris_podman_tcp
    - chris_queue
    - chris_scheduler
    - chris_swift
    - chris_worker
    - chris_worker_periodic
    - chris_dev
    - chris_ui
    - chris_store
    - chris_after
    - chris_plugins

```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by pcunning-rh** [comment]
Closed with https://github.com/team19hackathon2021/ChRIS_ultron_backEnd/commit/b78381d3ed69519144eb8e5f711e283d6fe774f4#diff-3b7b5bf04b54ad567a8f4b9dcd95c56990655ff76b7ff1c4b72ce382daa4c3c2 and https://github.com/team19hackathon2021/ChRIS_ultron_backEnd/commit/e6d50fad3db4a57c40329270e76978f3d88b0909#diff-3b7b5bf04b54ad567a8f4b9dcd95c56990655ff76b7ff1c4b72ce382daa4c3c2
