### ISSUE TITLE
define the ChRIS pman systemd service file.  

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-chris#50]
# Mission define the ChRIS pman systemd service file.  

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for ChRIS")

Your mission, should you choose to accept it, is define the ChRIS pman systemd service file.  . 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

ChRIS is a pervasively open source platform that utilizes cloud technologies to democratize medical analytics application development. It enables healthcare organizations to keep owning their data while benefiting from public cloud processing capabilities. ChRIS is developed as part of a collaborative effort between Boston Children’s Hospital, Red Hat, Boston University, and the Mass Open Cloud (MOC). ChRIS allows researchers the ability to simply deploy their applications in a cloud infrastructure with access to more data, more compute, and more collaboration to drive medical innovation. ChRIS uses leading open source technologies to standardize cloud-based healthcare application development, taking care of the infrastructure so medical researchers can focus on their data.

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/ChRIS_ultron_backEnd/tree/master/ansible

## create the code

Create a new file: /usr/local/src/ChRIS_ultron_backEnd/ansible/roles/chris_pman/templates/chris_pman.service

```plain
[Unit]
Description=
After=network.service

[Service]
Type=simple
User={{ APP_USER }}
ExecStart=/usr/bin/podman run --name {{ PMAN_NAME }}\{\% if APP_POD_NETWORK is defined \%\} --pod {{ PMAN_POD }}\{\% endif \%\}\{\% if APP_CONTAINER_NETWORK is defined \%\} --network {{ APP_CONTAINER_NETWORK }}\{\% endif \%\} -v {{ PMAN_SRC }}:/home/localuser/pman --rm -e "STOREBASE={{ APP_DATA }}" -e "SECRET_KEY={{ APP_SECRET_KEY }}" -e "CONTAINER_ENV=podman" -e 'PODMAN_IP_ADDRESS={{ PODMAN_IP_ADDRESS }}' {{ PMAN_IMAGE }}:{{ PMAN_VERSION }}
ExecStop=/usr/bin/podman rm {{ PMAN_NAME }} -f
Restart=on-failure

[Install]
WantedBy=multi-user.target

```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by jrangelramos** [comment]
PR Pushed for this issue https://github.com/team19hackathon2021/ChRIS_ultron_backEnd/pull/4

**Comment by pcunning-rh** [comment]
Closed with https://github.com/team19hackathon2021/ChRIS_ultron_backEnd/pull/4/files
