### ISSUE TITLE
define the Ansible tasks to install the pfcon application as a container in podman

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-chris#51]
# Mission define the Ansible tasks to install the pfcon application as a container in podman

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for ChRIS")

Your mission, should you choose to accept it, is define the Ansible tasks to install the pfcon application as a container in podman. 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

ChRIS is a pervasively open source platform that utilizes cloud technologies to democratize medical analytics application development. It enables healthcare organizations to keep owning their data while benefiting from public cloud processing capabilities. ChRIS is developed as part of a collaborative effort between Boston Children’s Hospital, Red Hat, Boston University, and the Mass Open Cloud (MOC). ChRIS allows researchers the ability to simply deploy their applications in a cloud infrastructure with access to more data, more compute, and more collaboration to drive medical innovation. ChRIS uses leading open source technologies to standardize cloud-based healthcare application development, taking care of the infrastructure so medical researchers can focus on their data.

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/ChRIS_ultron_backEnd/tree/master/ansible

## automate the setup of the ChRIS pfcon source code repository. 

Create a new file: /usr/local/src/ChRIS_ultron_backEnd/ansible/roles/chris_pfcon/tasks/main.yml

```plain
---
# automate the setup of the ChRIS pfcon source code repository. 
- name: Check for the {{ PFCON_NAME }} README file
  stat:
    path: "{{ PFCON_SRC }}/README.rst"
  register: PFCON_README
- name: Create the {{ PFCON_NAME }} source directory {{ PFCON_SRC }}
  file:
    name: "{{ PFCON_SRC }}"
    state: directory
    owner: "{{ USER_NAME }}"
  when: not PFCON_README.stat.exists
  become: true
- name: Clone the {{ PFCON_REPO }} source code into {{ PFCON_SRC }}
  git:
    repo: "{{ PFCON_REPO }}"
    dest: "{{ PFCON_SRC }}"
  when: not PFCON_README.stat.exists
- name: set SELinux permissions on {{ PFCON_SRC }}
  sefcontext:
    target: "{{ PFCON_SRC }}(/.*)?"
    setype: container_file_t
  become: true
  vars:
    ansible_python_interpreter: "{{ APP_PYTHON }}"
- name: reload SELinux policy to ensure that {{ APP_NAME }} is executable
  command: "restorecon -irv {{ PFCON_SRC }}"
  become: true

```

## Automate the deployment of ChRIS pfcon as a Podman container running as a Systemd service. 

```plain

# Automate the deployment of ChRIS pfcon as a Podman container running as a Systemd service. 
- name: Create the {{ PFCON_NAME }} systemd service {{ PFCON_SYSTEMD }}. 
  template:
    src: chris_pfcon.service
    dest: "{{ PFCON_SYSTEMD }}"
  become: true
  when: ansible_pkg_mgr != 'homebrew'
- name: Reload the services. 
  systemd:
    daemon_reload: true
  become: true
  when: ansible_pkg_mgr != 'homebrew'
- name: Start and enable the {{ PFCON_SERVICE }} service. 
  service:
    name: "{{ PFCON_SERVICE }}"
    enabled: true
    state: restarted
  become: true
  when: ansible_pkg_mgr != 'homebrew'

```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by mairin** [comment]
the issue #78 team is working on this

**Comment by pcunning-rh** [comment]
Closing with https://github.com/team19hackathon2021/ChRIS_ultron_backEnd/pull/10
