### ISSUE TITLE
define the Ansible tasks to setup ChRIS plugins

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-chris#57]
# Mission define the Ansible tasks to setup ChRIS plugins

![Mission](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for ChRIS")

Your mission, should you choose to accept it, is define the Ansible tasks to setup ChRIS plugins. 

## The day of the operation is October 26th, 2021

You will have 4 hours to complete your mission. 

ChRIS is a pervasively open source platform that utilizes cloud technologies to democratize medical analytics application development. It enables healthcare organizations to keep owning their data while benefiting from public cloud processing capabilities. ChRIS is developed as part of a collaborative effort between Boston Children’s Hospital, Red Hat, Boston University, and the Mass Open Cloud (MOC). ChRIS allows researchers the ability to simply deploy their applications in a cloud infrastructure with access to more data, more compute, and more collaboration to drive medical innovation. ChRIS uses leading open source technologies to standardize cloud-based healthcare application development, taking care of the infrastructure so medical researchers can focus on their data.

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service developing the code and automating the deployment to OpenShift. 

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/team19hackathon2021/ChRIS_ultron_backEnd/tree/master/ansible

## create the code

Create a new file: /usr/local/src/ChRIS_ultron_backEnd/ansible/roles/chris_plugin/tasks/main.yml

```plain
---
- name: Pull the plugin image {{ APP_PLUGIN.CONTAINER_REPO }}/{{ APP_PLUGIN.CONTAINER_IMAGE }}
  containers.podman.podman_image:
    name: "{{ APP_PLUGIN.CONTAINER_REPO }}/{{ APP_PLUGIN.CONTAINER_IMAGE }}"
    state: present
  become: true
- name: Gather facts on a specific container {{ APP_PLUGIN.CONTAINER_REPO }}/{{ APP_PLUGIN.CONTAINER_IMAGE }}
  containers.podman.podman_image_info:
    name: "{{ APP_PLUGIN.CONTAINER_REPO }}/{{ APP_PLUGIN.CONTAINER_IMAGE }}"
  register: CONTAINER_IMAGE_INFO
  become: true
- name: "Obtain the PLUGIN_REP for the ChRIS plugin: sudo podman run --rm {{ APP_PLUGIN.CONTAINER_REPO }}/{{ APP_PLUGIN.CONTAINER_IMAGE }} {{ CONTAINER_IMAGE_INFO.images[0].Config.Cmd[0] }} --json"
  shell: "/usr/bin/podman run --rm {{ APP_PLUGIN.CONTAINER_REPO }}/{{ APP_PLUGIN.CONTAINER_IMAGE }} {{ CONTAINER_IMAGE_INFO.images[0].Config.Cmd[0] }} --json"
  register: PLUGIN_REP_INFO
  become: true
- name: "Add the plugin to the ChRIS store {{ APP_PLUGIN.CONTAINER_REPO }}/{{ APP_PLUGIN.CONTAINER_IMAGE }}"
  shell: /usr/bin/podman exec {{ STORE_NAME }} python plugins/services/manager.py add "{{ APP_PLUGIN.CONTAINER_IMAGE }}" "{{ APP_SUPER_USER_NAME }}" https://github.com/FNNDSC "{{ APP_PLUGIN.CONTAINER_REPO }}/{{ APP_PLUGIN.CONTAINER_IMAGE }}" --descriptorstring '{{ PLUGIN_REP_INFO.stdout | to_json | from_json }}'
  register: PLUGIN_REP_INFO
  become: true
  ignore_errors: true
- name: "Add the ENV to ChRIS dev {{ APP_PLUGIN.CONTAINER_REPO }}/{{ APP_PLUGIN.CONTAINER_IMAGE }}^{{ APP_PLUGIN.CONTAINER_ENVIRONMENT | default('host') }}"
  shell: /usr/bin/podman exec {{ DEV_NAME }} python plugins/services/manager.py add "{{ APP_PLUGIN.CONTAINER_ENVIRONMENT | default('host') }}" "http://{{ PFCON_HOSTNAME }}:{{ PFCON_PORT }}/api/v1/" --description "{{ APP_PLUGIN.CONTAINER_ENVIRONMENT | default('host') }} Description"
  register: PLUGIN_ADD_ENV_INFO
  become: true
  ignore_errors: true
- name: "Register the ENV to ChRIS dev {{ APP_PLUGIN.CONTAINER_REPO }}/{{ APP_PLUGIN.CONTAINER_IMAGE }}^{{ APP_PLUGIN.CONTAINER_ENVIRONMENT | default('host') }}"
  shell: /usr/bin/podman exec {{ DEV_NAME }} python plugins/services/manager.py register "{{ APP_PLUGIN.CONTAINER_ENVIRONMENT | default('host') }}" --pluginname "{{ APP_PLUGIN.CONTAINER_IMAGE }}"
  register: PLUGIN_ADD_ENV_INFO
  become: true
  ignore_errors: true

```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by pcunning-rh** [comment]
Closed with https://github.com/team19hackathon2021/ChRIS_ultron_backEnd/pull/8
