### ISSUE TITLE
Improve pman application logging

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-chris#80]
![Hackathon Task for Team-19 Hackathon 2021](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Team-19 Hackathon 2021")

# Improve pman application logging

### Your mission should you choose to accept it: 

improve pman application logging

### Suggested skills: 

Python

### Create a directory for the pman repository and clone it

```bash
install -d -o $USER /usr/local/src/pman
git clone git@github.com:team19hackathon2021/pman.git /usr/local/src/pman
```

## Import the os package to get environment variables. 

```python
import os
```

## Add better logging for gunicorn. 

```python
    # logging
    gunicorn_error_logger = logging.getLogger('gunicorn.error')
    app.logger.handlers.extend(gunicorn_error_logger.handlers)
    app.logger.setLevel(logging.DEBUG)
```

**Comment by adityajariwala** [comment]
https://github.com/team19hackathon2021/pman/pull/3
