### ISSUE TITLE
Enable podman configuration variables in the pman application

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-chris#82]
![Hackathon Task for Team-19 Hackathon 2021](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Team-19 Hackathon 2021")

# Enable podman configuration variables in the pman application

### Your mission should you choose to accept it: 

enable podman configuration variables in the pman application

### Suggested skills: 

Python

### Create a directory for the pman repository and clone it

```bash
install -d -o $USER /usr/local/src/pman
git clone git@github.com:team19hackathon2021/pman.git /usr/local/src/pman
```

## Import the os package to get environment variables. 

```python
import os
```

## Update the self.CONTAINER_ENV variable to load it's default value from an environment variable. 

```python
        self.CONTAINER_ENV = env('CONTAINER_ENV', os.getenv('CONTAINER_ENV', 'swarm'))
```

## If the container environment is podman, set the docker environment variables. 

```python
        if self.CONTAINER_ENV == 'podman':
            docker_host = env('DOCKER_HOST', '')
            if docker_host:
                self.DOCKER_HOST = docker_host
            docker_tls_verify = env.int('DOCKER_TLS_VERIFY', None)
            if docker_tls_verify is not None:
                self.DOCKER_TLS_VERIFY = docker_tls_verify
            docker_cert_path = env('DOCKER_CERT_PATH', '')
            if docker_cert_path:
                self.DOCKER_CERT_PATH = docker_cert_path
```

**Comment by JAVGan** [comment]
PR sent

**Comment by pcunning-rh** [comment]
Closed with https://github.com/team19hackathon2021/pman/pull/2
