### ISSUE TITLE
Load the database host from an environment variable when migrating the database

### ISSUE THREAD

**Issue by computate** [team19hackathon2021/issues-chris#91]
![Hackathon Task for Team-19 Hackathon 2021](https://github.com/team19hackathon2021/team19-hackathon-2021/raw/master/static/png/image.png "Hackathon Task for Team-19 Hackathon 2021")

# Load the database host from an environment variable when migrating the database

### Your mission should you choose to accept it: 

load the database host from an environment variable when migrating the database

### Suggested skills: 

Python

### Create a directory for the ChRIS_ultron_backEnd repository and clone it

```bash
install -d -o $USER /usr/local/src/ChRIS_ultron_backEnd
git clone git@github.com:team19hackathon2021/ChRIS_ultron_backEnd.git /usr/local/src/ChRIS_ultron_backEnd
```

## Import the os package to get environment variables. 

```python
import os
```

## Load the database hostname from an environment variable. 

```python
host = os.getenv('DEV_DB_HOSTNAME')
if not host:
    host = args.host if args.host else 'localhost'
```

**Comment by pcunning-rh** [comment]
Closed with https://github.com/team19hackathon2021/ChRIS_ultron_backEnd/pull/14
